import * as stylex from "@stylexjs/stylex"
import Header from "~/ui/Header"

import "./globals.css"

const styles = stylex.create({
  base: {
    fontSize: 16,
    lineHeight: 1.5,
    color: "grey",
  },
  highlighted: {
    color: "rebeccapurple",
  },
})

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body {...stylex.props(styles.base, styles.highlighted)}>
        <Header />
        {children}
      </body>
    </html>
  )
}
