import * as stylex from "@stylexjs/stylex"

import "./globals.css"

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body {...stylex.props(styles.container)}>{children}</body>
    </html>
  )
}

const styles = stylex.create({
  container: {
    minHeight: "100vh",
    paddingTop: "32px",
    paddingBottom: "120px",
    paddingHorizontal: "32px",
    display: "flex",
  },
})
